// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SB.Repositories.Context;

#nullable disable

namespace SB.Repositories.Migrations
{
    [DbContext(typeof(SBDbContext))]
    partial class SBDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SB.Entities.Empleados.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset?>("FechaModifica")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaRegistra")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioModifica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioRegistra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Departamento", "RRHH");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Borrado = false,
                            Descripcion = "RRHH",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nombre = "Recursos Humanos",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Borrado = false,
                            Descripcion = "TI",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nombre = "Tecnología",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Borrado = false,
                            Descripcion = "Comercial",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nombre = "Ventas",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Borrado = false,
                            Descripcion = "Contabilidad",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nombre = "Finanzas",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Borrado = false,
                            Descripcion = "Operaciones",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nombre = "Operaciones",
                            UsuarioRegistra = "SYSTEM"
                        });
                });

            modelBuilder.Entity("SB.Entities.Empleados.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<int>("DepartmentoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FechaModifica")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaRegistra")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("HorasTrabajadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroSeguroSocial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioSemanal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SueldoPorHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarifaComision")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("TipoEmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioModifica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioRegistra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("VentasBrutas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentoId");

                    b.HasIndex("NumeroSeguroSocial")
                        .IsUnique();

                    b.HasIndex("TipoEmpleadoId");

                    b.ToTable("Empleado", "RRHH");

                    b.HasDiscriminator<int>("TipoEmpleadoId");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SB.Entities.Empleados.TipoEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset?>("FechaModifica")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaRegistra")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UsuarioModifica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioRegistra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoEmpleado", "RRHH");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Borrado = false,
                            Codigo = "001",
                            Descripcion = "Pago semanal fijo.",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nombre = "Empleado Asalariado",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Borrado = false,
                            Codigo = "002",
                            Descripcion = "Horas regulares + extras al 1.5×.",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nombre = "Empleado por Horas",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Borrado = false,
                            Codigo = "003",
                            Descripcion = "Ventas brutas × tarifa.",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nombre = "Empleado por Comisión",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Borrado = false,
                            Codigo = "004",
                            Descripcion = "Comisión + base + 10% del base.",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nombre = "Empleado Asalariado por Comisión",
                            UsuarioRegistra = "SYSTEM"
                        });
                });

            modelBuilder.Entity("SB.Entities.Seguridad.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Ip")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UsuarioRegistra")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("UsuarioRegistra");

                    b.HasIndex("Entidad", "EntidadId");

                    b.ToTable("Auditoria", "Seguridad");
                });

            modelBuilder.Entity("SB.Entities.Seguridad.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("FechaModifica")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaRegistra")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Icono")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioModifica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioRegistra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Modulo", "Seguridad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Borrado = false,
                            Codigo = "001",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icono = "ti-users",
                            Nombre = "Gestión de Empleados",
                            Orden = 1,
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Borrado = false,
                            Codigo = "002",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icono = "ti-user-shield",
                            Nombre = "Usuarios del Sistema",
                            Orden = 2,
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Borrado = false,
                            Codigo = "003",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icono = "ti-report",
                            Nombre = "Reportes",
                            Orden = 3,
                            UsuarioRegistra = "SYSTEM"
                        });
                });

            modelBuilder.Entity("SB.Entities.Seguridad.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset?>("FechaModifica")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaRegistra")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UsuarioModifica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioRegistra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ModuloId");

                    b.ToTable("Permiso", "Seguridad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Borrado = false,
                            Codigo = "EMPLEADOS_VER",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModuloId = 1,
                            Nombre = "Ver empleados",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Borrado = false,
                            Codigo = "EMPLEADOS_CREAR",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModuloId = 1,
                            Nombre = "Crear empleados",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Borrado = false,
                            Codigo = "EMPLEADOS_EDITAR",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModuloId = 1,
                            Nombre = "Editar empleados",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Borrado = false,
                            Codigo = "EMPLEADOS_INACTIVAR",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModuloId = 1,
                            Nombre = "Inactivar empleados",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Borrado = false,
                            Codigo = "USUARIOS_VER",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModuloId = 2,
                            Nombre = "Ver usuarios",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Borrado = false,
                            Codigo = "USUARIOS_CREAR",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModuloId = 2,
                            Nombre = "Crear usuarios",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Borrado = false,
                            Codigo = "AUDITORIA_VER",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModuloId = 2,
                            Nombre = "Ver bitácora",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Borrado = false,
                            Codigo = "REPORTES_VER",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModuloId = 3,
                            Nombre = "Ver reportes",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Borrado = false,
                            Codigo = "REPORTES_EXPORTAR",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModuloId = 3,
                            Nombre = "Exportar reportes",
                            UsuarioRegistra = "SYSTEM"
                        });
                });

            modelBuilder.Entity("SB.Entities.Seguridad.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaConcedida")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaModifica")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaRegistra")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioConcede")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioRegistra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolesPermisos", "Seguridad");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            PermisoId = 1,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2631), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 1,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 2,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2700), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 2,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 3,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2704), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 3,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 4,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2706), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 4,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 5,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2709), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 5,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 6,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2711), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 6,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 7,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2713), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 7,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 8,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2715), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 8,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 9,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2717), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 9,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 1,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2297), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 100,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 5,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2317), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 101,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 6,
                            Activo = true,
                            Borrado = false,
                            FechaConcedida = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaRegistra = new DateTimeOffset(new DateTime(2026, 5, 29, 19, 12, 12, 738, DateTimeKind.Unspecified).AddTicks(2321), new TimeSpan(0, -4, 0, 0, 0)),
                            Id = 102,
                            UsuarioConcede = "SYSTEM",
                            UsuarioRegistra = ""
                        });
                });

            modelBuilder.Entity("SB.Entities.Seguridad.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("FechaModifica")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaRegistra")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UsuarioModifica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioRegistra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Roles", "Seguridad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Borrado = false,
                            Codigo = "ADMIN",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nombre = "Administrador",
                            UsuarioRegistra = "SYSTEM"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Borrado = false,
                            Codigo = "USUARIO",
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nombre = "Usuario",
                            UsuarioRegistra = "SYSTEM"
                        });
                });

            modelBuilder.Entity("SB.Entities.Seguridad.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaCambioContrasena")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaModifica")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaRegistra")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UltimoAcceso")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UsuarioModifica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioRegistra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", "Seguridad");
                });

            modelBuilder.Entity("SB.Entities.Empleados.BaseEmpleadoComision", b =>
                {
                    b.HasBaseType("SB.Entities.Empleados.Empleado");

                    b.HasDiscriminator().HasValue(4);

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Apellidos = "Vásquez",
                            Borrado = false,
                            DepartmentoId = 3,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 0m,
                            Nombres = "Elena",
                            NumeroSeguroSocial = "001-4000010-0",
                            SalarioBase = 500.00m,
                            SalarioSemanal = 0m,
                            SueldoPorHora = 0m,
                            TarifaComision = 0.08m,
                            TipoEmpleadoId = 4,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 15000.00m
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Apellidos = "Sosa",
                            Borrado = false,
                            DepartmentoId = 3,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 0m,
                            Nombres = "Daniel",
                            NumeroSeguroSocial = "001-4000011-1",
                            SalarioBase = 800.00m,
                            SalarioSemanal = 0m,
                            SueldoPorHora = 0m,
                            TarifaComision = 0.06m,
                            TipoEmpleadoId = 4,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 22000.00m
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Apellidos = "Polanco",
                            Borrado = false,
                            DepartmentoId = 3,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 0m,
                            Nombres = "Karen",
                            NumeroSeguroSocial = "001-4000012-2",
                            SalarioBase = 600.00m,
                            SalarioSemanal = 0m,
                            SueldoPorHora = 0m,
                            TarifaComision = 0.10m,
                            TipoEmpleadoId = 4,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 9500.00m
                        });
                });

            modelBuilder.Entity("SB.Entities.Empleados.EmpleadoAsalariado", b =>
                {
                    b.HasBaseType("SB.Entities.Empleados.Empleado");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellidos = "Ramírez",
                            Borrado = false,
                            DepartmentoId = 1,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 0m,
                            Nombres = "Carlos",
                            NumeroSeguroSocial = "001-1000001-1",
                            SalarioBase = 0m,
                            SalarioSemanal = 1200.00m,
                            SueldoPorHora = 0m,
                            TarifaComision = 0m,
                            TipoEmpleadoId = 1,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 0m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellidos = "Núñez",
                            Borrado = false,
                            DepartmentoId = 4,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 0m,
                            Nombres = "Patricia",
                            NumeroSeguroSocial = "001-1000002-2",
                            SalarioBase = 0m,
                            SalarioSemanal = 1850.50m,
                            SueldoPorHora = 0m,
                            TarifaComision = 0m,
                            TipoEmpleadoId = 1,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 0m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellidos = "Hernández",
                            Borrado = false,
                            DepartmentoId = 2,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 0m,
                            Nombres = "Luis",
                            NumeroSeguroSocial = "001-1000003-3",
                            SalarioBase = 0m,
                            SalarioSemanal = 2100.00m,
                            SueldoPorHora = 0m,
                            TarifaComision = 0m,
                            TipoEmpleadoId = 1,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 0m
                        });
                });

            modelBuilder.Entity("SB.Entities.Empleados.EmpleadoComision", b =>
                {
                    b.HasBaseType("SB.Entities.Empleados.Empleado");

                    b.HasDiscriminator().HasValue(3);

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Apellidos = "Reyes",
                            Borrado = false,
                            DepartmentoId = 3,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 0m,
                            Nombres = "Sandra",
                            NumeroSeguroSocial = "001-3000007-7",
                            SalarioBase = 0m,
                            SalarioSemanal = 0m,
                            SueldoPorHora = 0m,
                            TarifaComision = 0.05m,
                            TipoEmpleadoId = 3,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 12000.00m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Apellidos = "Tavárez",
                            Borrado = false,
                            DepartmentoId = 3,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 0m,
                            Nombres = "Jorge",
                            NumeroSeguroSocial = "001-3000008-8",
                            SalarioBase = 0m,
                            SalarioSemanal = 0m,
                            SueldoPorHora = 0m,
                            TarifaComision = 0.07m,
                            TipoEmpleadoId = 3,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 25500.00m
                        },
                        new
                        {
                            Id = 9,
                            Activo = false,
                            Apellidos = "Marte",
                            Borrado = false,
                            DepartmentoId = 3,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 0m,
                            Nombres = "Isabel",
                            NumeroSeguroSocial = "001-3000009-9",
                            SalarioBase = 0m,
                            SalarioSemanal = 0m,
                            SueldoPorHora = 0m,
                            TarifaComision = 0.06m,
                            TipoEmpleadoId = 3,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 8750.00m
                        });
                });

            modelBuilder.Entity("SB.Entities.Empleados.EmpleadoPorHoras", b =>
                {
                    b.HasBaseType("SB.Entities.Empleados.Empleado");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellidos = "Pérez",
                            Borrado = false,
                            DepartmentoId = 5,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 38.00m,
                            Nombres = "Andrés",
                            NumeroSeguroSocial = "001-2000004-4",
                            SalarioBase = 0m,
                            SalarioSemanal = 0m,
                            SueldoPorHora = 18.50m,
                            TarifaComision = 0m,
                            TipoEmpleadoId = 2,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 0m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apellidos = "Castillo",
                            Borrado = false,
                            DepartmentoId = 5,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 50.00m,
                            Nombres = "Mariela",
                            NumeroSeguroSocial = "001-2000005-5",
                            SalarioBase = 0m,
                            SalarioSemanal = 0m,
                            SueldoPorHora = 22.00m,
                            TarifaComision = 0m,
                            TipoEmpleadoId = 2,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 0m
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Apellidos = "Mejía",
                            Borrado = false,
                            DepartmentoId = 2,
                            FechaRegistra = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorasTrabajadas = 45.00m,
                            Nombres = "Roberto",
                            NumeroSeguroSocial = "001-2000006-6",
                            SalarioBase = 0m,
                            SalarioSemanal = 0m,
                            SueldoPorHora = 25.75m,
                            TarifaComision = 0m,
                            TipoEmpleadoId = 2,
                            UsuarioRegistra = "SYSTEM",
                            VentasBrutas = 0m
                        });
                });

            modelBuilder.Entity("SB.Entities.Empleados.Empleado", b =>
                {
                    b.HasOne("SB.Entities.Empleados.Departamento", "Departmento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartmentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SB.Entities.Empleados.TipoEmpleado", "TipoEmpleado")
                        .WithMany("Empleados")
                        .HasForeignKey("TipoEmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departmento");

                    b.Navigation("TipoEmpleado");
                });

            modelBuilder.Entity("SB.Entities.Seguridad.Permiso", b =>
                {
                    b.HasOne("SB.Entities.Seguridad.Modulo", "Modulo")
                        .WithMany("Permisos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("SB.Entities.Seguridad.RolPermiso", b =>
                {
                    b.HasOne("SB.Entities.Seguridad.Permiso", "Permiso")
                        .WithMany("RolePermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SB.Entities.Seguridad.Role", "Rol")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SB.Entities.Seguridad.Usuario", b =>
                {
                    b.HasOne("SB.Entities.Seguridad.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SB.Entities.Empleados.Departamento", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("SB.Entities.Empleados.TipoEmpleado", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("SB.Entities.Seguridad.Modulo", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("SB.Entities.Seguridad.Permiso", b =>
                {
                    b.Navigation("RolePermisos");
                });

            modelBuilder.Entity("SB.Entities.Seguridad.Role", b =>
                {
                    b.Navigation("RolesPermisos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
